board:
  - [r, n, b, q, k, b, n, r]
  - [., ., ., ., ., ., ., .]
  - [., ., ., ., ., ., ., .]
  - [., ., ., ., ., ., ., .]
  - [., ., ., ., ., ., ., .]
  - [., ., ., ., ., ., ., .]
  - [., ., ., ., ., ., ., .]
  - [R, N, B, Q, K, B, N, R]
